### ISSUE TITLE
Frends.FTP.DownloadFiles task timeouts too soon.

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.FTP#11]
Task gives timeout exception after 15 seconds even if the option is set to 60. The buffer size might be culprit in this.
https://frendscom.slack.com/archives/C03MZEPC941/p1657003698270509

**Comment by ttossavainen** [comment]
Timeout seems to be ok. Connect.BufferSize's default value is 32 bytes instead of 32 KBs. For an example Config.LocalFileBufferSize's default value is 4096 (=4 KB).

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.FTP/pull/20
