### ISSUE TITLE
Frends.FTP.UploadFiles has default value in ClientCertificatePath

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.FTP#12]
Task has default value in ClientCertificatePath which makes it impossible to give empty value to the field. This should be disabled when using the EnableClientAuth option.

**Comment by ttossavainen** [comment]
Also fixed Connect.BufferSize's documentation and default value. Similar case https://github.com/FrendsPlatform/Frends.FTP/issues/11

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.FTP/pull/23
