### ISSUE TITLE
Frends.FTP.UploadFiles doesn't document all the return fields.

### ISSUE THREAD

**Issue by MMIK0** [FrendsPlatform/Frends.FTP#15]
https://github.com/FrendsPlatform/Frends.FTP/blob/8231ea4b1317f0fb3928911a8e37d2d0650d06bb/Frends.FTP.UploadFiles/Frends.FTP.UploadFiles/FTP.cs#L98 Doesn't document all return fields, eg. TransferredFileNames

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.FTP/pull/23
