### ISSUE TITLE
Frends.FTP.UploadFiles task needs better operations log

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.FTP#18]
The operations log needs improvements. For example if timeout exception is thrown when connecting to server, no operations log is created at all. Task only throws exception: Timed out trying to read data from the socket stream!.

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.FTP/pull/27

**Comment by ttossavainen** [comment]
merged
